project:
  type: book
  output-dir: docs

book:
  title: "CASA0023 Learning Diary"
  author: "Yuet Yung Lung (22082423)"
  date: "24/03/2023"
  navbar:
    logo: img/earth.png
    collapse: true
    collapse-below: sm
    background: primary
    foreground: light
    search: true
  sidebar:
    style: floating
    reader-mode: true
    search: false
  chapters:
    - index.qmd
    - week_1.qmd
    - week_2.qmd
    - week_3.qmd
    - week_4.qmd
    - week_5.qmd
    - week_6.qmd
    - week_7.qmd
    - week_8.qmd
    - references.qmd
  page-navigation: true

bibliography: references.bib

format:
  html:
    theme: minty
  pdf:
    documentclass: scrreprt

editor: visual
