# Week 1: Introduction to Remote Sensing

## Summary

Remote sensing provides an approach to collect, store and extract environmental information from satellite image without direct contact[@Robinson1978]. With the variety of available platforms, understanding the characteristics and difference between sensors presents an importance when studying ground features for a specific study area. When considering the suitability of satellite imagery, the user should concern about the basic characteristics:

1.  *Type of sensor*

    Passive sensor measures radiance emitted or reflected by earth-atmospheric system, while active sensor emits EMR waves and measure 'back-scattered' radiation. Mentioned by @jorgensen_remote_2008, although passive sensor doesn't requires energy source and rely on solar radiation, it presents multiple limitation regarding the requirement of daylight, adverse impact by weather and cloud cover, and lack of ability to obtain information for the bottom of feature. Oppositely, other than the ability to operate in day or night and penetrate cloud cover, radar system is also widely adopted for acquiring digital elevation data as signals from most systems can penetrate through canopy or even dry ground [@jorgensen_remote_2008].

2.  *Resolution*

    The resolution of imagery can be analysed in spatial, spectral, temporal and radiometric aspects, which is determined by the specification of platform and sensors. @liang_chapter_2020 provided a detailed summary for characteristics of commonly used satellite sensor:

![Resolution of commonly used satellite sensor [@liang_chapter_2020]](img/Capture.JPG){fig-align="center" width="371"}

3.  *Data format*

    Majority of remote sensing imagery is raster data, but data from radar system can also provide vertical information as lidar can make direct measurement of structure.

This week's practical explores on the data acquisition, pre-processing and basic analysis of satellite imagery in QGIS, SNAP and R. In the pre-processing of imagery for spectral signature analysis, one question that I found interesting to investigate is the upscale or downscale of bands in resampling of data. To perform masking for study area, bands with various spatial resolution requires resampling to have a consistent resolution. Considering the level of details presented in high spatial resolution, I wonder what are the factors that we should consider during the decision of upscale or downscale of image. This question was investigated by @UrielKitron2006Uoda in their research of public health, which it is pointed out that there is always a temptation to extrapolate from fine-resolution data or interpolate from coarse resolution. The article discussed that coarse resolution may lost the spatial heterogeneity on the micro-scale, while a fine resolution will fails to detect the general patterns on the macro-scale. Authors approached this question by adjusting the scale of their study of diseases and analyse the achievable observations. The conclusion is both resolutions can successfully describe dispersion pattern or process of dispersal from different geographical level data, but the similarity behind is having a solid understanding of the system in time and space according to the purpose of study.

## Applications

Having comprehensive data source with various resolutions, remote sensing is widely applied in geospatial and environmental studies. According to @liang_chapter_2020, application of remote sensing can be categorized into 4 main categories:

![Application of remote sensing product [@liang_chapter_2020]](img/Capture_1.JPG){fig-align="center" width="322"}

Definition of each category is summarised below with related study as example.

1.  *Detection and Monitoring*

    Using remote sensing data to characterise the surface dynamics and interactions from natural environment and human activities

    Research Example:

    Remote sensing is often applied to drought monitoring and forecasting as it allows observations in large temporal and spatial scales. @VanajithV2021MDuM utilised Sentinel-2 data to calculate the Normalized Difference Vegetation Index, Normalized Difference Water Index and Vegetation Condition Index for monitoring drought condition over Solapur city, India. Authors used multispectral satellite images due to the provision of a wide range of bands with high resolution and low radiometric calibration uncertainty. The result successfully identified the constant drought conditions and demonstrated the suitability of these indices for drought monitoring.

2.  *Driving numerical models and decision support systems*

    Using remote sensing data as input data for environmental related models and decision support systems

    Research Example:

    @randin_monitoring_2020 used remote sensing to monitor biodiversity in the Anthropocene for species distribution models, because remote sensing is able to provide reliable data that is spatially comprehensive and time-sensitive about the key factors driving the distribution in biodiversity. A monitoring approach that the authors suggested was taking advantage of temporal stacking of available time series to capture the niche of species and actual distribution, while increasing the transferability of ecological model [@randin_monitoring_2020].

3.  *Validating model simulations*

    Using remote sensing data to retrieve parameters for validation of numerical models

    Research Example:

    Crop coefficient can be predicted from fraction of ground cover and vegetation height by using ground data and remote sensing, where remote sensing vegetation indices can also be used to validate the computation of parameters for maize, barley and olives [@pereira_prediction_2020].

4.  *Data assimilation into numerical models*

    Data assimilation allows estimation of unknowns in model based of available information within a time window. Remote sensing data can be incorporated with measurement data and used in parameter adjustment.

    Research Example:

    @Nair2022 introduced how remote sensing data in data assimilation to improve initial estimates for hydrollogical and atmospheric modelling, such as providing soil moisture data at unprecedented spatiotemporal resolutions across different scale for streamflow simulation, which can be complemented with in-situ surface and root zone observations for the calibration of model parameters.

These 4 categories effectively provide an insight on the diverse application of remote sensing data, from solely apply for detection, operation of numerical models and validation of models, to using incorporately for estimation of model parameters. The research examples showed that with utilisation of band features can provide estimation through band composition and indices, thus increase the possibility of applying remote sensing imagery with different numerical models. Study by @randin_monitoring_2020 also demonstrated that user can take advantage of the temporal resolution of remote sensing to obtain long-term series data for testing the temporal transferability of model.

## Reflection

Content in week 1 provides an overview on how data from different platforms can be processed and manipulated to study the spectral significance of ground features. The part that I found interesting is the application of tasseled cap transformation in the study of image statistics. The transformation integrates original image data to new coordinate system by formulating brightness, greenness, wetness according to the spectral signature in bands. Band math increase the range of application of remote sensing data, which is also reflected in the research examples for calculation of indices and coefficients. From previous section, I also had a better understanding on how utilisation of data characteristics can lead to a wider application in different study areas, such as applying time series data to increase transferability in monitoring of changes. The advancement of remote sensing platforms will provide data with better resolution, and further enhance the flexibility of study in different scale and model application.
